#ifdef __OBJC__
#import <UIKit/UIKit.h>
#else
#ifndef FOUNDATION_EXPORT
#if defined(__cplusplus)
#define FOUNDATION_EXPORT extern "C"
#else
#define FOUNDATION_EXPORT extern
#endif
#endif
#endif

#import "MDAssetCutter.h"
#import "MDAssetPassthrough.h"
#import "MDAssetProcessProtocol.h"
#import "MDRecordARVideoCamera.h"
#import "MDRecordCamera.h"
#import "MDRecordCameraAdapter.h"
#import "MDFastMP4Handler.h"
#import "MP4Fast.h"
#import "MDBBGPUImageSlidingFilter.h"
#import "MDGPUImageMediaFiltersAttachment.h"
#import "MDRecordColorDazzledFilter.h"
#import "MDRecordColorPackingFilter.h"
#import "MDRecordGraffitiEffectFilter.h"
#import "MDRecordLayerRenderFilter.h"
#import "MDRecordMirrImageFrameFilter.h"
#import "MDRecordOverlayFilter.h"
#import "MDRecordRainWindowFilter.h"
#import "MDRecordShakeFilter.h"
#import "MDRecordSoulOutFilter.h"
#import "MDRecordTVArtifactFilter.h"
#import "SplitPersonFilter.h"
#import "SplitPersonVerticalFilter.h"
#import "WaterReflectionFilter.h"
#import "MDError.h"
#import "MDMediaEditorContext.h"
#import "MDProcessImageProtocol.h"
#import "MDRAnalytics.h"
#import "MDRAnalyticsSession.h"
#import "MDRecordFilter.h"
#import "MDRecordLoggerKey.h"
#import "MDRecordManager.h"
#import "MDRecordUtils.h"
#import "MDRIRecordLogger.h"
#import "MDDeviceMotionObserver.h"
#import "MDImageBlender.h"
#import "MDRecordAuthorization.h"
#import "MDRecordDeviceType.h"
#import "MDRecordPlatformUtils.h"
#import "MDRenderContext.h"
#import "NSData+MDMD5Hash.h"
#import "NSString+MDMD5Hash.h"
#import "PHPhotoLibrary+MDSaveAsset.h"
#import "UIImage+MDConversion.h"
#import "UIView+MDSnapshot.h"
#import "MDAssetExportOperation.h"
#import "MDCancellable.h"
#import "MDRecordExportProgressUpdater.h"
#import "MDVideoCompositeExport.h"
#import "MDVideoExport.h"
#import "MDVideoExportProtocol.h"
#import "MDRecordAssetReversedManager.h"
#import "MDRecordAssetReverseOperation.h"
#import "MDRecordAssetReverserSession.h"
#import "MDRecordVideoSegment.h"
#import "MDAssetWriter.h"
#import "MDCameraVideoRecording.h"
#import "MDCameraVideoSegmentsManager.h"
#import "MDRecordSpeedVaryDocument.h"
#import "MDCameraEditorContext.h"
#import "MDRecordingSimpleAdapter.h"
#import "MDImageEditorContext.h"
#import "MDImageSimpleEditorAdapter.h"
#import "MDAssetAudioComposite.h"
#import "MDAssetBGMAudioComposite.h"
#import "MDAssetGetAudioTracks.h"
#import "MDAssetOperationDecorator.h"
#import "MDAssetRepeat.h"
#import "MDAssetVideoTransform.h"
#import "MDAssetPorcessBuilder.h"
#import "MDVideoAssetProcessBuilder.h"
#import "MDVideoEditorContext.h"
#import "MDRecordPlayerViewController.h"
#import "MDRecordVideoFilterPlugin.h"
#import "MDVideoSimpleEditorAdapter.h"

FOUNDATION_EXPORT double RecordSDKVersionNumber;
FOUNDATION_EXPORT const unsigned char RecordSDKVersionString[];

